.TH "char_array" 3 "Wed Jan 16 2013" "latticenoise" \" -*- nroff -*-
.ad l
.nh
.SH NAME
char_array \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const dropt_char * \fBs\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A string that might not be NUL-terminated\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for latticenoise from the source code\&.
