.TH "help_params" 3 "Wed Jan 16 2013" "latticenoise" \" -*- nroff -*-
.ad l
.nh
.SH NAME
help_params \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdropt_help_params\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhelp_params\fP & \fBset_indent\fP (unsigned int numSpaces)"
.br
.ti -1c
.RI "\fBhelp_params\fP & \fBset_description_start_column\fP (unsigned int col)"
.br
.ti -1c
.RI "\fBhelp_params\fP & \fBset_blank_lines_between_options\fP (bool enable)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for latticenoise from the source code\&.
