.TH "dropt_stringstream" 3 "Wed Jan 16 2013" "latticenoise" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dropt_stringstream \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "dropt_char * \fBstring\fP"
.br
.ti -1c
.RI "size_t \fBmaxSize\fP"
.br
.ti -1c
.RI "size_t \fBused\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for latticenoise from the source code\&.
