.TH "src/latticenoise.c" 3 "Wed Jan 16 2013" "latticenoise" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/latticenoise.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'latticenoise\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'limits\&.h'\fP
.br
\fC#include 'time\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBln_lattice\fP \fBln_lattice_new\fP (unsigned int dimensions, unsigned int dim_length, \fBln_rng_func_def\fP *rng_func)"
.br
.ti -1c
.RI "float \fBln_lattice_value1\fP (\fBln_lattice\fP lattice, unsigned int x)"
.br
.ti -1c
.RI "float \fBln_lattice_value2\fP (\fBln_lattice\fP lattice, unsigned int x, unsigned int y)"
.br
.ti -1c
.RI "float \fBln_lattice_value3\fP (\fBln_lattice\fP lattice, unsigned int x, unsigned int y, unsigned int z)"
.br
.ti -1c
.RI "float \fBln_lattice_value4\fP (\fBln_lattice\fP lattice, unsigned int x, unsigned int y, unsigned int z, unsigned int w)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBlatticenoise\&.h\fP
.PP
Main implementation\&. 
.SH "Function Documentation"
.PP 
.SS "\fBln_lattice\fP ln_lattice_new (unsigned intdimensions, unsigned intdim_length, \fBln_rng_func_def\fP *rng_func)"
Creates a new lattice, allocates the memory needed and feeds it with values\&.
.PP
The lattice has an upper bound of (2 ^ 32) - 1 values\&.
.PP
\fBParameters:\fP
.RS 4
\fIdimensions\fP How many dimensions the lattice has\&. It must be >= 1\&. 
.br
\fIdim_length\fP The size in one dimension of the lattice\&. It must be >= 1\&. The total size is pow(dim_length, dimensions)\&. 
.br
\fIrng_func\fP A pointer to a ln_rng_func_def\&. This parameter is optional, leave it to NULL to use the default C RNG\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A new lattice object on success\&. NULL if: dimensions < 1 dim_length < 1 pow(dim_length, dimensions) > MAX(unsigned int) memory could not be allocated (out of memory\&.) 
.RE
.PP

.SS "float ln_lattice_value1 (\fBln_lattice\fPlattice, unsigned intx)"
Retrieves a value from a 1D lattice\&.
.PP
\fBReturns:\fP
.RS 4
The value at coordinate x in the lattice or infinity if lattice\&.dimensions != 1 or the coordinate are out of bounds\&. 
.RE
.PP

.SS "float ln_lattice_value2 (\fBln_lattice\fPlattice, unsigned intx, unsigned inty)"
Retrieves a value from a 2D lattice\&.
.PP
\fBReturns:\fP
.RS 4
The value at coordinates (x, y) in the lattice or infinity if lattice\&.dimensions != 2 or the coordinates are out of bounds\&. 
.RE
.PP

.SS "float ln_lattice_value3 (\fBln_lattice\fPlattice, unsigned intx, unsigned inty, unsigned intz)"
Retrieves a value from a 3D lattice\&.
.PP
\fBReturns:\fP
.RS 4
The value at coordinates (x, y, z) in the lattice or infinity if lattice\&.dimensions != 3 or the coordinates are out of bounds\&. 
.RE
.PP

.SS "float ln_lattice_value4 (\fBln_lattice\fPlattice, unsigned intx, unsigned inty, unsigned intz, unsigned intw)"
Retrieves a value from a 4D lattice\&.
.PP
\fBReturns:\fP
.RS 4
The value at coordinates (x, y, z, w) in the lattice or infinity if lattice\&.dimensions != 4 or the coordinates are out of bounds\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for latticenoise from the source code\&.
