.TH "md_readme" 3 "Wed Jan 16 2013" "latticenoise" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_readme \- latticenoise 
A small C library and executable for generating procedural textures\&.
.PP
Note: At the moment no buildable version exists\&.
.PP
.SS "About the code"
.PP
The code is standard complaint C99 code\&.
.PP
.SS "Documentation"
.PP
Coming soon\&.
.PP
.SS "License"
.PP
The main library is under a BSD License\&. For more information, check each individual file\&.
.PP
The dropt-library is bundled\&. It is only used by the executables, and not \fBlatticenoise\&.h\fP and \fBlatticenoise\&.c\fP\&. For more information check the dropt-sources under lib\&. 
