.TH "point_s" 3 "Wed Jan 16 2013" "latticenoise" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <latticenoise\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a three dimensional point in space\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for latticenoise from the source code\&.
